// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1JKgsFz95E8FTfSvzoqzH4UdT5YTuGg',
    appId: '1:523775229517:web:1f169bdcac0b78193ca604',
    messagingSenderId: '523775229517',
    projectId: 'cenec-app',
    authDomain: 'cenec-app.firebaseapp.com',
    databaseURL: 'https://cenec-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cenec-app.appspot.com',
    measurementId: 'G-09N12RJ55G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSOMW1ph5DBNGF4B8Cr18D44MtHUBEyEk',
    appId: '1:523775229517:android:e34ac8a779679e583ca604',
    messagingSenderId: '523775229517',
    projectId: 'cenec-app',
    databaseURL: 'https://cenec-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cenec-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGIr8XFOnL2McLiYfY4kGLWJB3PNJ2OJo',
    appId: '1:523775229517:ios:baec931cca84b9fb3ca604',
    messagingSenderId: '523775229517',
    projectId: 'cenec-app',
    databaseURL: 'https://cenec-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cenec-app.appspot.com',
    androidClientId: '523775229517-mcr638869kk32l6vqrpjjcmm2n5qaroe.apps.googleusercontent.com',
    iosClientId: '523775229517-2vmg7gh0et3bqo3rbf6106mhlgnocbli.apps.googleusercontent.com',
    iosBundleId: 'com.example.cenecApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGIr8XFOnL2McLiYfY4kGLWJB3PNJ2OJo',
    appId: '1:523775229517:ios:baec931cca84b9fb3ca604',
    messagingSenderId: '523775229517',
    projectId: 'cenec-app',
    databaseURL: 'https://cenec-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cenec-app.appspot.com',
    androidClientId: '523775229517-mcr638869kk32l6vqrpjjcmm2n5qaroe.apps.googleusercontent.com',
    iosClientId: '523775229517-2vmg7gh0et3bqo3rbf6106mhlgnocbli.apps.googleusercontent.com',
    iosBundleId: 'com.example.cenecApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1JKgsFz95E8FTfSvzoqzH4UdT5YTuGg',
    appId: '1:523775229517:web:8144ee08e0b4aaa93ca604',
    messagingSenderId: '523775229517',
    projectId: 'cenec-app',
    authDomain: 'cenec-app.firebaseapp.com',
    databaseURL: 'https://cenec-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cenec-app.appspot.com',
    measurementId: 'G-9QEQC01829',
  );
}
